"""Add field about_me and last_seen in model user

Revision ID: ae03466d7ace
Revises: 8421197b4fc1
Create Date: 2021-10-24 21:53:29.383352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae03466d7ace'
down_revision = '8421197b4fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    op.create_table('ingredients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingredient', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ingredients_pkey')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('shipper_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name='customers_pkey')
    )
    op.create_table('followers',
    sa.Column('sns_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('follower_ids', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sns_id', 'follower_ids', name='followers_pkey')
    )
    op.create_table('play_with_json',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('json_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='play_with_json_pkey')
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey'),
    sa.UniqueConstraint('name', name='test_name_key')
    )
    op.create_table('products',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=11, scale=2), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['product_group.group_id'], name='products_group_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', name='products_pkey')
    )
    op.create_index('idx_product_id', 'products', ['product_id'], unique=False)
    op.create_table('product_group',
    sa.Column('group_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('group_id', name='product_group_pkey')
    )
    op.create_table('family',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True)
    )
    op.create_table('grab',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('shipper',
    sa.Column('shipper_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('shipper_id', name='shipper_pkey')
    )
    # ### end Alembic commands ###
